// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3424367380822371137),
      name: 'Observation',
      lastPropertyId: const obx_int.IdUid(12, 8168925267553886702),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6031402812819408716),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3828678865794108054),
            name: 'titulo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8925096630492898907),
            name: 'descricao',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1139640663474757439),
            name: 'geocode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4918524851979683985),
            name: 'public',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8147017902691182910),
            name: 'slugs',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 503478028279901766),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1370959147381740906),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2878386142544550188),
            name: 'imageFile',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2895364834393000375),
            name: 'emailController',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 320866325285365533),
            name: 'nameOfSlug',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8168925267553886702),
            name: 'userGroupSlug',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1246914406462267874),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(10, 1501759433518433140),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4405420550469633872),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8913870619812095136),
            name: 'nome',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8860483678062242320),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 166331598035111785),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8445835222691172937),
            name: 'filePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3293055597656285),
            name: 'nrObs',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 266383684661387131),
            name: 'subSlug',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 37843524002608217),
            name: 'subSlugname',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3204324535171595924),
            name: 'userGroupsName',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1501759433518433140),
            name: 'userGroupsSlug',
            type: 30,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1246914406462267874),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Observation: obx_int.EntityDefinition<Observation>(
        model: _entities[0],
        toOneRelations: (Observation object) => [],
        toManyRelations: (Observation object) => {},
        getId: (Observation object) => object.id,
        setId: (Observation object, int id) {
          object.id = id;
        },
        objectToFB: (Observation object, fb.Builder fbb) {
          final tituloOffset =
              object.titulo == null ? null : fbb.writeString(object.titulo!);
          final descricaoOffset = object.descricao == null
              ? null
              : fbb.writeString(object.descricao!);
          final geocodeOffset =
              object.geocode == null ? null : fbb.writeString(object.geocode!);
          final slugsOffset =
              object.slugs == null ? null : fbb.writeString(object.slugs!);
          final imageFileOffset = object.imageFile == null
              ? null
              : fbb.writeList(object.imageFile!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final emailControllerOffset = object.emailController == null
              ? null
              : fbb.writeString(object.emailController!);
          final nameOfSlugOffset = object.nameOfSlug == null
              ? null
              : fbb.writeString(object.nameOfSlug!);
          final userGroupSlugOffset = object.userGroupSlug == null
              ? null
              : fbb.writeString(object.userGroupSlug!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, tituloOffset);
          fbb.addOffset(2, descricaoOffset);
          fbb.addOffset(3, geocodeOffset);
          fbb.addBool(4, object.public);
          fbb.addOffset(5, slugsOffset);
          fbb.addFloat64(6, object.latitude);
          fbb.addFloat64(7, object.longitude);
          fbb.addOffset(8, imageFileOffset);
          fbb.addOffset(9, emailControllerOffset);
          fbb.addOffset(10, nameOfSlugOffset);
          fbb.addOffset(11, userGroupSlugOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final tituloParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final descricaoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final geocodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final publicParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 12);
          final slugsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final latitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 16);
          final longitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 18);
          final imageFileParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 20);
          final emailControllerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final nameOfSlugParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final userGroupSlugParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final object = Observation(
              id: idParam,
              titulo: tituloParam,
              descricao: descricaoParam,
              geocode: geocodeParam,
              public: publicParam,
              slugs: slugsParam,
              latitude: latitudeParam,
              longitude: longitudeParam,
              imageFile: imageFileParam,
              emailController: emailControllerParam,
              nameOfSlug: nameOfSlugParam,
              userGroupSlug: userGroupSlugParam);

          return object;
        }),
    User: obx_int.EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final usernameOffset = object.username == null
              ? null
              : fbb.writeString(object.username!);
          final filePathOffset = object.filePath == null
              ? null
              : fbb.writeString(object.filePath!);
          final subSlugOffset = object.subSlug == null
              ? null
              : fbb.writeList(
                  object.subSlug!.map(fbb.writeString).toList(growable: false));
          final subSlugnameOffset = object.subSlugname == null
              ? null
              : fbb.writeList(object.subSlugname!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final userGroupsNameOffset = object.userGroupsName == null
              ? null
              : fbb.writeList(object.userGroupsName!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final userGroupsSlugOffset = object.userGroupsSlug == null
              ? null
              : fbb.writeList(object.userGroupsSlug!
                  .map(fbb.writeString)
                  .toList(growable: false));
          fbb.startTable(11);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, usernameOffset);
          fbb.addOffset(4, filePathOffset);
          fbb.addInt64(5, object.nrObs);
          fbb.addOffset(6, subSlugOffset);
          fbb.addOffset(7, subSlugnameOffset);
          fbb.addOffset(8, userGroupsNameOffset);
          fbb.addOffset(9, userGroupsSlugOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final filePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final nrObsParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final subSlugParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 16);
          final subSlugnameParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 18);
          final userGroupsNameParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 20);
          final userGroupsSlugParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 22);
          final object = User(
              id: idParam,
              nome: nomeParam,
              email: emailParam,
              username: usernameParam,
              filePath: filePathParam,
              nrObs: nrObsParam,
              subSlug: subSlugParam,
              subSlugname: subSlugnameParam,
              userGroupsName: userGroupsNameParam,
              userGroupsSlug: userGroupsSlugParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Observation] entity fields to define ObjectBox queries.
class Observation_ {
  /// See [Observation.id].
  static final id =
      obx.QueryIntegerProperty<Observation>(_entities[0].properties[0]);

  /// See [Observation.titulo].
  static final titulo =
      obx.QueryStringProperty<Observation>(_entities[0].properties[1]);

  /// See [Observation.descricao].
  static final descricao =
      obx.QueryStringProperty<Observation>(_entities[0].properties[2]);

  /// See [Observation.geocode].
  static final geocode =
      obx.QueryStringProperty<Observation>(_entities[0].properties[3]);

  /// See [Observation.public].
  static final public =
      obx.QueryBooleanProperty<Observation>(_entities[0].properties[4]);

  /// See [Observation.slugs].
  static final slugs =
      obx.QueryStringProperty<Observation>(_entities[0].properties[5]);

  /// See [Observation.latitude].
  static final latitude =
      obx.QueryDoubleProperty<Observation>(_entities[0].properties[6]);

  /// See [Observation.longitude].
  static final longitude =
      obx.QueryDoubleProperty<Observation>(_entities[0].properties[7]);

  /// See [Observation.imageFile].
  static final imageFile =
      obx.QueryStringVectorProperty<Observation>(_entities[0].properties[8]);

  /// See [Observation.emailController].
  static final emailController =
      obx.QueryStringProperty<Observation>(_entities[0].properties[9]);

  /// See [Observation.nameOfSlug].
  static final nameOfSlug =
      obx.QueryStringProperty<Observation>(_entities[0].properties[10]);

  /// See [Observation.userGroupSlug].
  static final userGroupSlug =
      obx.QueryStringProperty<Observation>(_entities[0].properties[11]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// See [User.nome].
  static final nome = obx.QueryStringProperty<User>(_entities[1].properties[1]);

  /// See [User.email].
  static final email =
      obx.QueryStringProperty<User>(_entities[1].properties[2]);

  /// See [User.username].
  static final username =
      obx.QueryStringProperty<User>(_entities[1].properties[3]);

  /// See [User.filePath].
  static final filePath =
      obx.QueryStringProperty<User>(_entities[1].properties[4]);

  /// See [User.nrObs].
  static final nrObs =
      obx.QueryIntegerProperty<User>(_entities[1].properties[5]);

  /// See [User.subSlug].
  static final subSlug =
      obx.QueryStringVectorProperty<User>(_entities[1].properties[6]);

  /// See [User.subSlugname].
  static final subSlugname =
      obx.QueryStringVectorProperty<User>(_entities[1].properties[7]);

  /// See [User.userGroupsName].
  static final userGroupsName =
      obx.QueryStringVectorProperty<User>(_entities[1].properties[8]);

  /// See [User.userGroupsSlug].
  static final userGroupsSlug =
      obx.QueryStringVectorProperty<User>(_entities[1].properties[9]);
}
